version: '3'

services:

  weather-data-generator:
    build:
      context: .
    image: weather-data-generator
    container_name: weather-data-generator
    restart: always
    environment:
      KAFKA_BROKER_1: 'kafka1:9092'
      KAFKA_TOPIC: weather-api-data
    networks:
      - riset-lakehouse-networks

networks:
  riset-lakehouse-networks:
    external: true