version: '3.8'
services:
  spark-master:
    image: spark-custom:latest
    build:
      context: .
    command: bin/spark-class org.apache.spark.deploy.master.Master
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - riset-lakehouse-networks

  spark-worker:
    image: spark-custom:latest
    build:
      context: .
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 3
      SPARK_WORKER_MEMORY: 4g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - riset-lakehouse-networks

networks:
  riset-lakehouse-networks:
    external: True