version: '3.8'
services:
  jobmanager:
    image: flink_customs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobmanager
    command: jobmanager
    hostname: jobmanager
    ports:
      - "8088:8081"
    environment:
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: jobmanager
      rest.flamegraph.enabled: true
    networks:
      - riset-lakehouse-networks
    volumes:
      - ./usr_jobs:/opt/flink/jobs

  taskmanager:
    image: flink_customs
    build:
      context: .
      dockerfile: Dockerfile
    hostname: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    networks:
      - riset-lakehouse-networks
    volumes:
      - ./usr_jobs:/opt/flink/jobs

networks:
  riset-lakehouse-networks:
    external: true