version: '3.8'
services:
  flink-jobmanager:
    image: flink_customs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flink-jobmanager
    hostname: flink-jobmanager
    ports:
      - "8088:8081"
    # environment:
    #   - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    #   - AWS_ACCESS_KEY_ID=minio
    #   - AWS_SECRET_ACCESS_KEY=minio123
    command: jobmanager
    networks:
      - riset-lakehouse-networks
    volumes:
      - ./usr_jobs:/opt/flink/jobs

  flink-taskmanager:
    image: flink_customs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flink-taskmanager
    hostname: flink-taskmanager
    depends_on:
      - flink-jobmanager
    # environment:
    #   - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    #   - AWS_ACCESS_KEY_ID=minio
    #   - AWS_SECRET_ACCESS_KEY=minio123    
    command: taskmanager
    networks:
      - riset-lakehouse-networks
    volumes:
      - ./usr_jobs:/opt/flink/jobs

networks:
  riset-lakehouse-networks:
    external: true