version: '3.8'

services:
  hive-metadata-postgres:
    image: postgres
    container_name: hive-metadata-postgres
    hostname: hive-metadata-postgres
    restart: always
    environment:
      POSTGRES_DB: hivemetastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5434:5432"
    volumes:
      - hive-metadata-postgres-volumes:/var/lib/postgresql/data
    networks:
      - riset-lakehouse-networks


  hive-metastore:
    image: naushadh/hive-metastore
    container_name: hive-metastore
    environment:
      DATABASE_HOST: hive-metadata-postgres
      DATABASE_DB: hivemetastore
      DATABASE_USER: hive
      DATABASE_PASSWORD: hive
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT_URL: http://minio:9000
      S3_BUCKET: hive
      S3_PREFIX: warehouse
    depends_on:
      - hive-metadata-postgres
    ports:
      - 9083:9083
    networks:
      - riset-lakehouse-networks

networks:
  riset-lakehouse-networks:
    external: True

volumes:
  hive-metadata-postgres-volumes:
    driver: local
    name: hive-metadata-postgres-volumes