version: '3.8'

services:
  hive-metadata-postgres:
    image: postgres
    container_name: hive-metadata-postgres
    hostname: hive-metadata-postgres
    restart: always
    environment:
      POSTGRES_DB: hivemetastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5434:5432"
    # volumes:
    #   - hive-metadata-postgres-volumes:/var/lib/postgresql/data
    networks:
      - riset-lakehouse-networks


  hive-metastore:
    image: naushadh/hive-metastore
    container_name: hive-metastore
    environment:
      DATABASE_HOST: hive-metadata-postgres
      DATABASE_DB: hivemetastore
      DATABASE_USER: hive
      DATABASE_PASSWORD: hive
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT_URL: http://minio:9000
      S3_BUCKET: hive
      S3_PREFIX: hive
    depends_on:
      - hive-metadata-postgres
    ports:
      - 9083:9083
    networks:
      - riset-lakehouse-networks


  # hive-metastore:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   image: hive-metastore
  #   container_name: hive-metastore
  #   depends_on:
  #     - hive-metadata-postgres
  #   environment:
  #     SERVICE_NAME: metastore
  #     HIVE_METASTORE_DATABASE_HOST: postgres
  #     HIVE_METASTORE_DATABASE_PORT: 5432
  #     HIVE_METASTORE_DATABASE_NAME: metastore
  #     HIVE_METASTORE_DATABASE_USER: hive
  #     HIVE_METASTORE_DATABASE_PASSWORD: hive
  #   command: ["hive", "--service", "metastore"]
  #   volumes:
  #     - ./conf/hive-site.xml:/opt/hive/conf/hive-site.xml
  #   ports:
  #     - "9083:9083"

  #   networks:
  #     - riset-lakehouse-networks

# version: '3.7'
# services:
#   mariadb:
#     image: 'mariadb:latest'
#     container_name: mariadb
#     hostname: mariadb
#     ports:
#       - '3306:3306'
#     environment:
#       MYSQL_ROOT_PASSWORD: admin
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: admin
#       MYSQL_DATABASE: metastore_db
#     networks:
#       - riset-lakehouse-networks

#   hive-metastore:
#     hostname: hive-metastore
#     container_name: hive-metastore
#     image: 'bitsondatadev/hive-metastore:latest'
#     ports:
#       - '9083:9083' # Metastore Thrift
#     volumes:
#       - ./config/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
#     environment:
#       METASTORE_DB_HOSTNAME: mariadb
#     depends_on:
#       - mariadb
#     networks:
#       - riset-lakehouse-networks

networks:
  riset-lakehouse-networks:
    external: True

volumes:
  hive-metadata-postgres-volumes:
    driver: local
    name: hive-metadata-postgres-volumes