version: '3.8'
services:
  flights_db:
    image: rahilwisdom/flights-database:latest
    container_name: flights_db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - flights_db_volume:/var/lib/postgresql/data
    networks:
      - riset-lakehouse-networks

networks:
  riset-lakehouse-networks:
    external: True

volumes:
  flights_db_volume:
    name: flights_db_volume
    driver: local